### ISSUE TITLE
Exit Error

### ISSUE THREAD

**Issue by mpavlak2018** [pingryiRT/ChatInterface#8] opened 2017-10-10 00:13 UTC
When /exit is typed, connected nodes receive this error:
```Exception in thread Thread-14:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/MitchellPavlak/PythonProjects/P2PPlatform/Network.py", line 179, in autoReceiver
    m = message_from_xml(rawXML)
  File "/Users/MitchellPavlak/PythonProjects/P2PPlatform/Message.py", line 81, in message_from_xml
    root = ET.fromstring(xml)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1301, in XML
    return parser.close()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1654, in close
    self._raiseerror(v)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
ParseError: no element found: line 1, column 0
```

**Comment by mpavlak2018** [comment] 2017-10-10 00:21
Additionally, I believe that when the node that types /exit was not the last node to send a message (received a message), there is another error on the /exit as well--> 
```
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 1073, in run
    self.function(*self.args, **self.kwargs)
  File "/Users/MitchellPavlak/PythonProjects/P2PPlatform/Network.py", line 171, in autoReceiver
    receiveOpen,writeOpen,errorSocks = select.select(sockList,[],[],2)#kind of bad,
error: (9, 'Bad file descriptor')
```

**Comment by jorndorff** [comment] 2017-10-22 19:30
I can reproduce at least the first error above, and I think the relevant part is:
```
  File ".../P2PPlatform/Network.py", line 180, in autoReceiver
    m = message_from_xml(rawXML)
  File ".../P2PPlatform/Message.py", line 81, in message_from_xml
    root = ET.fromstring(xml)
```
When a user `/exit`s an empty message is sent. When we later assume the message is valid xml and try to create a `Message` object out of it, the program crashes. So the new question is why does an empty message get sent?

**Comment by jorndorff** [comment] 2017-10-30 02:28
I'm closing this for now, because it seems to have been fixed over in P2PPlatform in https://github.com/pingryiRT/P2PPlatform/commit/bce952321e0e74f91f155d7d9cd1e608ee7ae2f7

But if let's try to remember the empty message I discovered above just in case it turns out to be relevant.

**Closed as completed by jorndorff** 2017-10-30 02:28 UTC
